name: Rust

on:
  push:
    branches: [ "main", "full" ]
  pull_request:
    branches: [ "main", "full" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update
      run: rustup default x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
